### ISSUE TITLE
i think it still points towards wrong direction >_>

### ISSUE THREAD

**Issue by allanwalpy** [Brawaru/marct#1]
https://github.com/Brawaru/marct/blob/d8512410b55717df463f7ff1f371e23f470b42b6/main.go#L3
 `tree/main` part is absent

**Comment by brawaru** [comment]
And this is how you can know someone never worked with Go 👀

 `github.com/brawaru/marct` is the package name, all that follows is the path within the package itself.

You can learn more about it here: https://go.dev/doc/code
